### ISSUE TITLE
Not connecting through proxy

### ISSUE THREAD

**Issue by Lorkster** [justinleewells/pogo-optimizer#23] opened 2016-07-20 09:14 UTC
Using:
OSX for pogo-optimizer
IOS 9 for PoGo

As soon as i enter the proxy under "manual proxy" for the wifi network (running WPA2-PSK), no traffic leaves the phone anymore. I've checked that both computer and phone are on the same wifi etc.

On the phone I have to add the certificate before adding the proxy, since I can't access the page with the cert otherwise.

Trying to access anything using Safari on the phone yields "No network connection" errors and PoGo never gets past the login.

Any idea whatsoever about what can be going on?

**Comment by n2o** [comment] 2016-07-20 11:34
Duplicate of #8

**Comment by Lorkster** [comment] 2016-07-20 12:29
Updated IOS 9.3.3 to see if that resolved the issue, it did not. Some combination of forgetting and re-adding the access point and proxy settings did though.

It has now managed to read my inventory, but it's not parsing it for the GUI.

**Closed** 2016-07-20 12:30 UTC
