### ISSUE TITLE
Error can not find ca.pem

### ISSUE THREAD

**Issue by humminfrey** [justinleewells/pogo-optimizer#136] opened 2016-07-27 12:02 UTC
Getting this error, (npm debug log at this link)

[https://drive.google.com/open?id=0B0cnobneC8qyTEJTSzEza25tUkE](url)

`
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.http-mitm-proxy/certs/ca.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/malhotrag/Documents/PoGo/pogo-optimizer/index.js:20:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.3.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.3.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.
`

**Comment by nubs** [comment] 2016-07-27 12:52
Duplicate of #133

**Comment by justinleewells** [comment] 2016-07-27 14:35
Fixed in justinleewells/pogo-optimizer@29dfdd5

**Closed by justinleewells** 2016-07-27 14:35 UTC
