### ISSUE TITLE
Spreadsheet: very slow due to lots of errors in DevTools console

### ISSUE THREAD

**Issue by mathiasbynens** [justinleewells/pogo-optimizer#160] opened 2016-07-28 12:00 UTC
Using the current HEAD version (c7b5a72e4cd553670077f0262f165c6b2915c2f4), opening the spreadsheet page and leaving it open for a few seconds results in _over 14 thousand_ error messages in the DevTools console for me. This makes the whole page extremely slow (even when the console is closed).

The first error logged is:

```
angular.js:13920 Error: [$interpolate:interr] Can't interpolate: ui celled table inverted {{moveColorClass() + ' ' + ivColorClass()}}
TypeError: Cannot read property 'move' of undefined
http://errors.angularjs.org/1.5.8/$interpolate/interr?p0=ui%20celled%20tabl…7D%7D&p1=TypeError%3A%20Cannot%20read%20property%20'move'%20of%20undefined
    at angular.js:68
    at Function.$interpolateMinErr.interr (angular.js:12085)
    at interpolationFn (angular.js:12414)
    at Object.attrInterpolatePreLinkFn (angular.js:9825)
    at angular.js:1247
    at invokeLinkFn (angular.js:9934)
    at nodeLinkFn (angular.js:9314)
    at compositeLinkFn (angular.js:8620)
    at compositeLinkFn (angular.js:8623)
    at compositeLinkFn (angular.js:8623)(anonymous function) @ angular.js:13920(anonymous function) @ angular.js:10467interpolationFn @ angular.js:12414attrInterpolatePreLinkFn @ angular.js:9825(anonymous function) @ angular.js:1247invokeLinkFn @ angular.js:9934nodeLinkFn @ angular.js:9314compositeLinkFn @ angular.js:8620compositeLinkFn @ angular.js:8623compositeLinkFn @ angular.js:8623publicLinkFn @ angular.js:8500(anonymous function) @ angular-ui-router.js:4105(anonymous function) @ angular.js:1247invokeLinkFn @ angular.js:9934nodeLinkFn @ angular.js:9335compositeLinkFn @ angular.js:8620publicLinkFn @ angular.js:8500lazyCompilation @ angular.js:8844updateView @ angular-ui-router.js:4023(anonymous function) @ angular-ui-router.js:3972$broadcast @ angular.js:18005(anonymous function) @ angular-ui-router.js:3353processQueue @ angular.js:16383(anonymous function) @ angular.js:16399$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790done @ angular.js:11831completeRequest @ angular.js:12033requestLoaded @ angular.js:11966
angular.js:13920
```

The rest of the errors logged are things like:

```
TypeError: Cannot read property 'move' of undefined
    at Scope.$scope.moveColorClass (spreadsheet.controller.js:131)
    at Array.fn0 (eval at compile (angular.js:14817), <anonymous>:4:732)
    at expressionInputsWatch (angular.js:15966)
    at Scope.$digest (angular.js:17515)
    at Scope.$apply (angular.js:17790)
    at done (angular.js:11831)
    at completeRequest (angular.js:12033)
    at XMLHttpRequest.requestLoaded (angular.js:11966)

TypeError: cannot read property move_2 of undefined […]

TypeError: cannot read property move_dps of undefined […]
```

**Comment by justinleewells** [comment] 2016-07-28 12:51
Ah, so this is causing the slow down that some other people were mentioning. Thank you so much for finding this.

**Comment by justinleewells** [comment] 2016-07-28 13:14
This should be fixed in justinleewells/pogo-optimizer#5f1e54f. I'll reopen if the error persists for you.

**Closed by justinleewells** 2016-07-28 13:14 UTC

**Comment by mathiasbynens** [comment] 2016-07-28 13:24
Looks like b4ec96401fa96d983cf499003d29eed6d296f170 didn’t fix it — I’m still getting the errors and the resulting slowdown (even after clearing my cache). It is working for you?

**Comment by justinleewells** [comment] 2016-07-28 13:27
The problem is that it never occurred for me haha. I always delete my player data, which should fix the error for everyone else, but I'd like to make it so they don't have to mess with their data.

**Comment by justinleewells** [comment] 2016-07-28 13:37
Okay, this should definitely do it justinleewells/pogo-optimizer@cf2e887.
